### ISSUE TITLE
Null ref spam on solid motor sep

### ISSUE THREAD

**Issue by raidernick** [sarbian/SmokeScreen#20]
When separating a solid motor that uses smokescreen/realplume, once it gets outside of physics range it starts null ref spam in the log. This spam doesn't happen if you switch to the solid before it leaves physics range. It also stops if you switch ships/return to space center and back.

Here is an album showing the simplest way to reproduce this: http://imgur.com/a/qg26D

Here is the error that is spammed:

NullReferenceException
  at (wrapper managed-to-native) UnityEngine.GameObject:get_transform ()

  at ModelMultiParticlePersistFX.Update () [0x00000] in <filename unknown>:0 
 
(Filename:  Line: -1)

**Comment by sarbian** [comment]
Fixed in 25ba6b17c8ae5f1fa480b888e82cb29f24a75cd1 / v2.6.7
