### ISSUE TITLE
NullRef in map view

### ISSUE THREAD

**Issue by DerpyFirework** [sarbian/SmokeScreen#27]
When in map view with a craft containing a part with a MODEL_MULTI_PARTICLE_PERSIST, a NullReferanceException is spammed in the log

SmokeScreen 2.6.14.0
ModuleManager 2.6.21
KSP 1.1.0.1196 (x64), Windows 7 x64

[output_log.txt and MM patch used](https://www.dropbox.com/sh/lqnnbt0k6urm9q6/AAAZaVcxWvzB4BwhOCHvmx1ca?dl=0)

**Comment by sarbian** [comment]
Can you try with this version and tell me if if does better ? I only had the NRE when existing the scene so I am not sure this was the same one.
https://ksp.sarbian.com/jenkins/job/SmokeScreen/55/artifact/SmokeScreen-2.6.15.0.zip

**Comment by DerpyFirework** [comment]
Issue is fixed, no NullRefs in map view. Many Thanks for the hard work!
