### ISSUE TITLE
Jumping landers

### ISSUE THREAD

**Issue by Kerbas-ad-astra** [sarbian/SmokeScreen#28]
2.6.20 has fixed the mach/reentry FX from being applied to exhaust particles, but there's still an issue where the exhaust seems to still have a spurious collider (which leads to landers being pushed up ~5 meters, and often tilted in a funny direction, when they're loaded from the map screen or quickloading).  The DisableCollider method is coming before the ground contact in the log (when I tested with a recompile with that debug statement re-enabled), but the ground contact error is still reading something hanging below the engine.

**Comment by Kerbas-ad-astra** [comment]
Just tried using "GetComponent**s**" (in case there were multiple colliders), but of course the fix is not that simple... :/

**Comment by sarbian** [comment]
Fixed with 38151f12aaeee18cc706e5c1ce6bd16661646213
