### ISSUE TITLE
Feature Request - Ability to adjust colour saturation of particle against pressure/altitude

### ISSUE THREAD

**Issue by Poodmund** [sarbian/SmokeScreen#31]
Some good SmokeScreen implementations still look slightly odd in low atmospheric pressure environments as the particles being used still have their, typically, yellow/orange tint whereas you'd expect a more white, desaturated mist at this point.

If there was a way that the particle tint could be desaturated against a pressure/altitude curve it may be useful to improve the aesthetic of some modded plumes.

**Comment by zorg2044** [comment]
Just to add to this, the ability adjust particle transparency would be greatly appreciated if at all possible. Right now plume translucency is controlled via emission only but with some particles it can look quite weird when emission drops too low which can make transitions or throttle down effects look odd. 

A transparency curve could be very helpful in such situations with emission being used to cut off plumes after visually fading out. Thanks for considering!
